Telephone_Number
Marwa-Sadat/Telephone_Number pull request #1
Opened 2024-06-29 08:55 UTC by Marwa-Sadat

1. *Objective:* An app was developed to verify if a given telephone number meets specified formatting rules, ensuring accurate and consistent phone number entries. 📞✔
2. *Inputs:* Users can input their telephone numbers into a designated field. ✏
3. *Validation Logic:* The app accurately checks the formatting of the entered telephone numbers. 🔄
4. *Error Handling:* Users are alerted if their input does not match the required format. 🚫❗
5. *User Interface:* A clean and intuitive interface was designed to enhance user experience. 🎨📱
6. *Responsiveness:* The app is fully responsive and functions well on all devices. 🌐📲
7. *Deployment:* The app was successfully hosted online, ensuring easy access for users. 🌐
![Screenshot 2024-06-29 122216](https://github.com/Marwa-Sadat/Telephone_Number/assets/168111110/0e6b222f-b806-4da2-846c-ad9ac55458a5)

2024-07-04 15:46 UTC, ahzamir commented
@Marwa-Sadat 

- I can not see your partner feedback

2024-07-04 18:41 UTC, Marwa-Sadat commented
![Screenshot 2024-07-02 155945](https://github.com/Marwa-Sadat/Telephone_Number/assets/168111110/27b03a8d-a50e-474e-ba90-04ca5c6f30e2)
Hi @zainabbehzad  I hope you are well, please check my project .

2024-07-04 18:43 UTC, Marwa-Sadat commented
![Screenshot 2024-07-04 220309](https://github.com/Marwa-Sadat/Telephone_Number/assets/168111110/c3b9ca11-b64a-4bd4-9c79-3de27d067222)
Hi @zinabbehzad I hope you are well, please check my project.

2024-07-05 04:24 UTC, zainabbehzad requested changes
🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validation project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your design is responsive
🧩Your repo has a professional README.md file

In your rREADME.md file you need some changes:

2024-07-05 04:24 UTC, zainabbehzad commented on README.md
> +
please add Demo of this project.

2024-07-05 04:24 UTC, zainabbehzad commented on README.md
> +  cd palindrome-checker
Please add name of this project

2024-07-05 10:42 UTC, Marwa-Sadat commented
@zainabbehzad I hope you are well, I did the feedback, please check my project again.

2024-07-05 12:30 UTC, zainabbehzad approved these changes
@Marwa-Sadat 

🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validation project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your design is responsive
✔Your repo has a professional README.md file
* Please do not forget to add Deployment Link of your project in README.md

2024-07-05 16:48 UTC, Marwa-Sadat commented
@ahzamir Hi sir  I hope you are well ,please check my project  sir.

2024-07-08 06:56 UTC, Marwa-Sadat commented
@ahzamir Hi sir I hope you are well ,please check my project sir.

2024-07-10 16:33 UTC, ahzamir approved these changes
### Hi @Marwa-Sadat 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Well done [OPTIONAL] just add some colors to your page to make it look more cool
- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/Marwa-Sadat/Telephone_Number/assets/96838030/63e4e621-74ec-48f6-86ea-0670a2acb3b4)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-08-15 15:58 UTC, merged